project_id = "sukyrypnsoyvlxrezlgv"

[functions]

[functions.check-usage-limits]
verify_jwt = false

[functions.generate-content-plan]
verify_jwt = false

[functions.regenerate-post]
verify_jwt = false

[functions.generate-shot-list]
verify_jwt = false

[functions.orchestrate-campaign]
verify_jwt = false