-- Add offers_promos field to content_plans table
-- This allows users to specify any offers/promotions that should be strategically used in posts
ALTER TABLE content_plans
  ADD COLUMN offers_promos TEXT CHECK (
    offers_promos IS NULL OR char_length(offers_promos) <= 300
  );

COMMENT ON COLUMN content_plans.offers_promos IS 'Optional promotional offers to strategically integrate into posts (e.g., "Buy $50 gift card, get $5 bonus" or "Weekend sale: 20% off"). If blank, AI will not invent promotions.';

-- Add content strategy fields to posts table
-- These fields store the strategic blueprint generated by the content plan agent
-- Caption, hook, and visual_concept will be filled later by specialized agents

ALTER TABLE posts
  ADD COLUMN strategy_type TEXT CHECK (strategy_type IN (
    'educational', 'promotional', 'engagement', 'testimonial', 'behind-the-scenes'
  )),
  ADD COLUMN purpose TEXT CHECK (
    purpose IS NULL OR char_length(purpose) <= 150
  ),
  ADD COLUMN core_message TEXT CHECK (
    core_message IS NULL OR char_length(core_message) <= 150
  ),
  ADD COLUMN behavioral_trigger TEXT CHECK (behavioral_trigger IN (
    'reciprocity', 'FOMO', 'scarcity', 'trust', 'nostalgia', 'belonging', 'curiosity', 'urgency'
  )),
  ADD COLUMN format TEXT,  -- reel, carousel, photo, story, video, update, offer, event, product
  ADD COLUMN tracking_focus TEXT CHECK (tracking_focus IN (
    'views', 'saves', 'shares', 'comments', 'clicks', 'DMs', 'redemptions', 'attendance'
  )),
  ADD COLUMN cta TEXT CHECK (
    cta IS NULL OR char_length(cta) <= 100
  );

-- Make caption and visual_concept nullable since they'll be generated by separate agents
-- Caption will be filled by copywriting agent
-- Visual_concept will be filled by shot list agent
ALTER TABLE posts
  ALTER COLUMN caption DROP NOT NULL,
  ALTER COLUMN visual_concept DROP NOT NULL;

-- Update the caption constraint to allow null
ALTER TABLE posts
  DROP CONSTRAINT IF EXISTS posts_caption_check;

ALTER TABLE posts
  ADD CONSTRAINT posts_caption_check CHECK (
    caption IS NULL OR char_length(caption) BETWEEN 10 AND 500
  );

-- Add indexes for commonly queried strategy fields
CREATE INDEX idx_posts_strategy_type ON posts(strategy_type) WHERE NOT deleted;
CREATE INDEX idx_posts_behavioral_trigger ON posts(behavioral_trigger) WHERE NOT deleted;
CREATE INDEX idx_posts_tracking_focus ON posts(tracking_focus) WHERE NOT deleted;

-- Add comments explaining the new fields
COMMENT ON COLUMN posts.strategy_type IS 'Content strategy classification: educational, promotional, engagement, testimonial, or behind-the-scenes. Generated by content plan agent.';
COMMENT ON COLUMN posts.purpose IS 'One-sentence objective for this post (≤150 chars). Example: "Build awareness of new matcha flavor launch". Generated by content plan agent.';
COMMENT ON COLUMN posts.core_message IS 'Main takeaway or value proposition (≤150 chars). Example: "Premium ceremonial-grade matcha meets artisan ice cream". Generated by content plan agent.';
COMMENT ON COLUMN posts.behavioral_trigger IS 'Primary psychological trigger to drive engagement: reciprocity, FOMO, scarcity, trust, nostalgia, belonging, curiosity, or urgency. Generated by content plan agent.';
COMMENT ON COLUMN posts.format IS 'Content format from blueprint (reel, carousel, photo, story, etc). May differ from post_type which is normalized to Instagram format types. Generated by content plan agent.';
COMMENT ON COLUMN posts.tracking_focus IS 'Primary KPI to measure success: views, saves, shares, comments, clicks, DMs, redemptions, or attendance. Aligns with funnel stage. Generated by content plan agent.';
COMMENT ON COLUMN posts.cta IS 'Specific call-to-action (≤100 chars). Example: "Visit In-Store", "DM for Inquiries", "Sign Up". Generated by content plan agent.';
COMMENT ON COLUMN posts.caption IS 'Actual post copy (10-500 chars). Generated by copywriting agent after blueprint is approved.';
COMMENT ON COLUMN posts.hook IS 'Attention-grabbing opening for reels/stories (≤100 chars). Generated by copywriting agent.';
COMMENT ON COLUMN posts.visual_concept IS 'Detailed visual execution plan with props, angles, lighting. Generated by shot list agent.';
